package project

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

const codexRulesContents = `# Generated by Fledge. Do not edit.

prefix_rule(
    pattern = ["fledge"],
    decision = "allow",
    justification = "Fledge project coordination commands are allowed outside the sandbox.",
    match = [
        "fledge init",
        "fledge agent spawn --name worker --harness codex",
    ],
)

prefix_rule(
    pattern = ["fledge", "start"],
    decision = "forbidden",
    justification = "Run fledge start directly in a user-controlled terminal.",
    match = [
        "fledge start",
        "fledge start --harness codex",
    ],
)

prefix_rule(
    pattern = ["fledge", "stop"],
    decision = "forbidden",
    justification = "Run fledge stop directly in a user-controlled terminal.",
    match = [
        "fledge stop",
        "fledge stop --yes",
    ],
)

prefix_rule(
    pattern = ["herdr", "agent", ["wait", "read", "get", "list", "prompt", "send-keys", "attach", "explain"]],
    decision = "forbidden",
    justification = "Agents must coordinate exclusively through Fledge messaging.",
    match = [
        "herdr agent wait worker",
        "herdr agent read worker",
        "herdr agent get worker",
        "herdr agent list",
        "herdr agent prompt worker status",
        "herdr agent send-keys worker Enter",
        "herdr agent attach worker",
        "herdr agent explain worker",
    ],
)

prefix_rule(
    pattern = ["herdr", "api", "snapshot"],
    decision = "forbidden",
    justification = "Use injected Fledge messages instead of inspecting Herdr session state.",
    match = [
        "herdr api snapshot",
    ],
)

# Herdr accepts global session selectors before its subcommand. Prefix rules
# cannot match the later agent operation across an arbitrary session or remote
# name, so reject these direct forms to prevent bypassing the agent rules above.
prefix_rule(
    pattern = ["herdr", ["--session", "--remote"]],
    decision = "forbidden",
    justification = "Use Fledge commands instead of direct session-scoped Herdr commands.",
    match = [
        "herdr --session project agent wait worker",
        "herdr --remote host agent prompt worker status",
    ],
)
`

const previousCodexRulesContents = `# Generated by Fledge. Do not edit.

prefix_rule(
    pattern = ["fledge"],
    decision = "allow",
    justification = "Fledge project coordination commands are allowed outside the sandbox.",
    match = [
        "fledge init",
        "fledge agent spawn --name worker --harness codex",
    ],
)

prefix_rule(
    pattern = ["fledge", "start"],
    decision = "forbidden",
    justification = "Run fledge start directly in a user-controlled terminal.",
    match = [
        "fledge start",
        "fledge start --harness codex",
    ],
)

prefix_rule(
    pattern = ["fledge", "stop"],
    decision = "forbidden",
    justification = "Run fledge stop directly in a user-controlled terminal.",
    match = [
        "fledge stop",
        "fledge stop --yes",
    ],
)
`

const legacyCodexRulesContents = previousCodexRulesContents + `
prefix_rule(
    pattern = ["herdr", "agent", ["wait", "read"]],
    decision = "allow",
    justification = "Read-only Herdr agent coordination commands are allowed outside the sandbox.",
    match = [
        "herdr agent wait worker",
        "herdr agent read worker",
    ],
    not_match = [
        "herdr agent start worker",
        "herdr session delete project",
    ],
)
`

// EnsureCodexRules installs the project-local Codex command policy without
// overwriting an existing file with different contents.
func EnsureCodexRules(root string) error {
	return ensureCodexRules(root, false)
}

func ensureCodexRulesForInit(root string) error {
	return ensureCodexRules(root, true)
}

func ensureCodexRules(root string, migrateLegacy bool) error {
	path := filepath.Join(root, ".codex", "rules", "fledge.rules")
	data, err := os.ReadFile(path)
	switch {
	case err == nil:
		if migrateLegacy && isLegacyCodexRules(data) {
			if err := os.WriteFile(path, []byte(codexRulesContents), 0o644); err != nil {
				return fmt.Errorf("update legacy Codex rule file %q: %w", path, err)
			}
			return nil
		}
		return validateCodexRules(path, data)
	case !errors.Is(err, os.ErrNotExist):
		return fmt.Errorf("read Codex rule file %q: %w", path, err)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create Codex rules directory: %w", err)
	}
	return createFile(path, []byte(codexRulesContents), 0o644, validateCodexRulesFile)
}

func validateCodexRulesFile(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read Codex rule file %q: %w", path, err)
	}
	return validateCodexRules(path, data)
}

func validateCodexRules(path string, data []byte) error {
	if bytes.Equal(data, []byte(codexRulesContents)) {
		return nil
	}
	if isLegacyCodexRules(data) {
		return fmt.Errorf(
			"Codex rule file %q uses Fledge's legacy generated policy; run fledge init to update it before launching Codex agents",
			path,
		)
	}
	return fmt.Errorf(
		"Codex rule file %q conflicts with Fledge's required policy; move or remove it, then rerun fledge init",
		path,
	)
}

func isLegacyCodexRules(data []byte) bool {
	return bytes.Equal(data, []byte(previousCodexRulesContents)) ||
		bytes.Equal(data, []byte(legacyCodexRulesContents))
}
